// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	Bidirectional(ctx context.Context, opts ...grpc.CallOption) (TestService_BidirectionalClient, error)
	ServerStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TestService_ServerStreamClient, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Bidirectional(ctx context.Context, opts ...grpc.CallOption) (TestService_BidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], "/com.example.grpc.v1.TestService/bidirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceBidirectionalClient{stream}
	return x, nil
}

type TestService_BidirectionalClient interface {
	Send(*Ping) error
	Recv() (*ServerEventMessage, error)
	grpc.ClientStream
}

type testServiceBidirectionalClient struct {
	grpc.ClientStream
}

func (x *testServiceBidirectionalClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *testServiceBidirectionalClient) Recv() (*ServerEventMessage, error) {
	m := new(ServerEventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testServiceClient) ServerStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TestService_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], "/com.example.grpc.v1.TestService/serverStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_ServerStreamClient interface {
	Recv() (*ServerEventMessage, error)
	grpc.ClientStream
}

type testServiceServerStreamClient struct {
	grpc.ClientStream
}

func (x *testServiceServerStreamClient) Recv() (*ServerEventMessage, error) {
	m := new(ServerEventMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	Bidirectional(TestService_BidirectionalServer) error
	ServerStream(*emptypb.Empty, TestService_ServerStreamServer) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) Bidirectional(TestService_BidirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method Bidirectional not implemented")
}
func (UnimplementedTestServiceServer) ServerStream(*emptypb.Empty, TestService_ServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_Bidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).Bidirectional(&testServiceBidirectionalServer{stream})
}

type TestService_BidirectionalServer interface {
	Send(*ServerEventMessage) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type testServiceBidirectionalServer struct {
	grpc.ServerStream
}

func (x *testServiceBidirectionalServer) Send(m *ServerEventMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *testServiceBidirectionalServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TestService_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).ServerStream(m, &testServiceServerStreamServer{stream})
}

type TestService_ServerStreamServer interface {
	Send(*ServerEventMessage) error
	grpc.ServerStream
}

type testServiceServerStreamServer struct {
	grpc.ServerStream
}

func (x *testServiceServerStreamServer) Send(m *ServerEventMessage) error {
	return x.ServerStream.SendMsg(m)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.example.grpc.v1.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "bidirectional",
			Handler:       _TestService_Bidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "serverStream",
			Handler:       _TestService_ServerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
